version: '3'

services:
  flask-ansible:
    build: .
    container_name: flask-ansible-ui
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ~/.ssh/id_rsa:/app/keys/id_rsa:ro
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
