---
- name: Configurar clúster Kubernetes
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Instalar Podman y dependencias
      dnf:
        name:
          - podman
          - containernetworking-plugins
          - containers-common
        state: latest

    - name: Crear configuración para Podman como runtime de Kubernetes
      copy:
        dest: /etc/containerd/config.toml
        content: |
          version = 2
          [plugins."io.containerd.grpc.v1.cri"]
            sandbox_image = "registry.k8s.io/pause:3.8"
          [plugins."io.containerd.grpc.v1.cri".containerd]
            default_runtime_name = "crio"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.crio]
            runtime_type = "io.containerd.runc.v2"

    - name: Iniciar y habilitar containerd
      service:
        name: containerd
        state: started
        enabled: yes

  roles:
    - common
    - { role: k8s-master, when: "'master' in group_names" }
    - { role: k8s-node, when: "'nodes' in group_names" }
